apiVersion: v1
kind: Service
metadata:
  labels:
  app: nginx
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
